  final List<Map<String, dynamic>> strategies = [
    {
      'name': 'Tit for Tat',
      'description': 'Cooperates first, then copies opponent\'s last move. Simple, forgiving, and highly successful in tournaments.',
      'behavior': 'C, then copy opponent\'s previous move',
      'strength': 'Simple, nice, retaliatory, forgiving',
      'weakness': 'Can get stuck in defection cycles',
      'example': 'Round 1: C\nOpponent plays D\nRound 2: D\nOpponent plays C\nRound 3: C',
    },
    {
      'name': 'Always Cooperate (Angel)',
      'description': 'Always chooses to cooperate, regardless of opponent\'s actions. Very trusting but vulnerable to exploitation.',
      'behavior': 'Always plays C',
      'strength': 'Maximizes mutual cooperation',
      'weakness': 'Easily exploited by defectors',
      'example': 'Round 1: C\nRound 2: C\nRound 3: C\n(Always cooperative)',
    },
    {
      'name': 'Always Defect (Devil)',
      'description': 'Always chooses to defect. Exploits cooperative opponents but performs poorly against other defectors.',
      'behavior': 'Always plays D',
      'strength': 'Exploits cooperative strategies',
      'weakness': 'Poor against other defectors',
      'example': 'Round 1: D\nRound 2: D\nRound 3: D\n(Always defects)',
    },
    {
      'name': 'Grudger',
      'description': 'Cooperates until opponent defects once, then defects forever. Unforgiving but effective against exploiters.',
      'behavior': 'C until opponent plays D, then always D',
      'strength': 'Punishes defection severely',
      'weakness': 'Unforgiving, no second chances',
      'example': 'Round 1: C\nRound 2: C\nOpponent plays D\nRound 3: D\nRound 4: D (forever)',
    },
    {
      'name': 'Random',
      'description': 'Randomly chooses between cooperation and defection with 50% probability each.',
      'behavior': '50% C, 50% D randomly',
      'strength': 'Unpredictable',
      'weakness': 'No strategic coherence',
      'example': 'Round 1: C (random)\nRound 2: D (random)\nRound 3: C (random)',
    },
    {
      'name': 'Pavlov (Win-Stay, Lose-Shift)',
      'description': 'Repeats last action if it was rewarding, changes if it wasn\'t. Adapts based on payoff received.',
      'behavior': 'Repeat if score ≥ 3, change if score < 3',
      'strength': 'Adapts based on success',
      'weakness': 'Can be exploited by pattern recognition',
      'example': 'Round 1: C, gets 3 points\nRound 2: C (won, so stay)\nGets 0 points\nRound 3: D (lost, so shift)',
    },
    {
      'name': 'Generous Tit for Tat',
      'description': 'Like Tit for Tat but occasionally forgives defections to break revenge cycles.',
      'behavior': 'Tit for Tat with ~10% forgiveness rate',
      'strength': 'Breaks defection cycles',
      'weakness': 'Can be exploited by recognizing forgiveness',
      'example': 'Opponent plays D\nUsually play D, but 10% chance play C',
    },
    {
      'name': 'Tit for Two Tats',
      'description': 'Only retaliates after opponent defects twice in a row. More forgiving than Tit for Tat.',
      'behavior': 'D only after opponent plays DD',
      'strength': 'Very forgiving, noise-tolerant',
      'weakness': 'Can be exploited by alternating CD',
      'example': 'Opponent: D, C, D, D\nResponse: C, C, C, D',
    },
    {
      'name': 'Suspicious Tit for Tat',
      'description': 'Like Tit for Tat but starts with defection instead of cooperation.',
      'behavior': 'D first, then copy opponent',
      'strength': 'Protects against initial exploitation',
      'weakness': 'Mutual defection if both suspicious',
      'example': 'Round 1: D\nOpponent plays C\nRound 2: C\nOpponent plays D\nRound 3: D',
    },
    {
      'name': 'Generous',
      'description': 'Cooperates most of the time but occasionally defects randomly to test opponent.',
      'behavior': '90% C, 10% D randomly',
      'strength': 'Mostly cooperative but not exploitable',
      'weakness': 'Random defections can trigger retaliation',
      'example': 'Usually cooperates, occasional random defection',
    },
  ];
